animations {
    enabled = true

    bezier = fluentDecel, 0.1, 1, 0, 1
    bezier = fluentAccel, 0.69, 0, 0.79, 0.18
    bezier = overshot, 0.05, 0.9, 0.1, 1.15
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92
    bezier = smoothPop, 0.22, 0.68, 0, 1.71
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.0
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = linear, 0.0, 0.0, 1.0, 1.0

    animation = windows, 1, 5, overshot, popin 60%
    animation = windowsIn, 1, 5, winIn, popin 60%
    animation = windowsOut, 1, 5, winOut, popin 80%
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 10, default
    animation = borderangle, 1, 100, linear, loop
    animation = fade, 1, 5, smoothIn
    animation = fadeIn, 1, 5, smoothIn
    animation = fadeOut, 1, 3, smoothOut
    animation = fadeDim, 1, 5, smoothIn
    animation = workspaces, 1, 5, wind, slide
    animation = specialWorkspace, 1, 5, smoothPop, slidefadevert -50%
    animation = layers, 1, 4, fluentDecel, popin 80%
    animation = layersIn, 1, 4, fluentDecel, popin 80%
    animation = layersOut, 1, 3, fluentAccel
}
