dwindle {
    preserve_split = true
    special_scale_factor = 0.85
    smart_split = false
    smart_resizing = true
}

master {
    new_status = master
    mfact = 0.55
    special_scale_factor = 0.85
}
