# =============================================================================
# File: ~/.config/hypr/windows.conf
# Description: Dwindle and Master tiling layout settings.
# =============================================================================

dwindle {
    preserve_split = true
    special_scale_factor = 0.8
}

master {
    new_status = master
    mfact = 0.55
    special_scale_factor = 0.8
}
