#!/usr/bin/env bash
# =============================================================================
# Script Name: layer5.sh
# Description: Layer 5 installer — GTK themes, icons, cursors, and fonts.
#
#              Installs and configures:
#                - GTK 3 / GTK 4 theming
#                - Icon theme (Papirus-Dark)
#                - Cursor theme (Bibata-Modern-Ice)
#                - Font packages
#                - Qt theming integration
#
# Usage:       bash install/layer5.sh
# Requires:    Layer 4 must be installed first.
#
# Author:      project_arch contributors
# Layer:       Layer 5 — Theming
# =============================================================================

set -euo pipefail

CURRENT_LAYER="Layer 5"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

# =============================================================================
# Package Definitions
# =============================================================================

readonly LAYER5_PACKAGES=(
    "gtk3"                        # GTK 3 toolkit
    "gtk4"                        # GTK 4 toolkit
    "gnome-themes-extra"          # Adwaita theme (dark mode support)
    "papirus-icon-theme"          # Papirus icon theme (with dark variant)
    "nwg-look"                    # GTK settings editor for Wayland
    "qt5ct"                       # Qt5 configuration tool (non-KDE)
    "qt6ct"                       # Qt6 configuration tool (non-KDE)
    "ttf-jetbrains-mono-nerd"     # JetBrains Mono Nerd Font
    "ttf-nerd-fonts-symbols"      # Nerd Font symbols
    "noto-fonts"                  # Google Noto fonts — wide Unicode coverage
    "noto-fonts-cjk"              # CJK font support
    "noto-fonts-emoji"            # Color emoji
    "ttf-liberation"              # Metric-compatible MS font replacements
    "ttf-font-awesome"            # Font Awesome icons (used in Waybar)
    "inter-font"                  # Inter — clean sans-serif UI font
)

readonly LAYER5_AUR_PACKAGES=(
    "bibata-cursor-theme"         # Bibata cursor theme
)

# =============================================================================
# Configuration Deployment
# =============================================================================

deploy_gtk_config() {
    log_info "Deploying GTK configuration..."

    # GTK 3
    local gtk3_dest="${XDG_CONFIG_HOME}/gtk-3.0"
    mkdir -p "${gtk3_dest}"
    if [[ -f "${REPO_ROOT}/gtk/gtk-3.0/settings.ini" ]]; then
        deploy_config "gtk/gtk-3.0/settings.ini" "${gtk3_dest}/settings.ini"
    fi

    # GTK 4
    local gtk4_dest="${XDG_CONFIG_HOME}/gtk-4.0"
    mkdir -p "${gtk4_dest}"
    if [[ -f "${REPO_ROOT}/gtk/gtk-4.0/settings.ini" ]]; then
        deploy_config "gtk/gtk-4.0/settings.ini" "${gtk4_dest}/settings.ini"
    fi

    # Qt5ct
    if [[ -f "${REPO_ROOT}/gtk/qt5ct.conf" ]]; then
        local qt5ct_dest="${XDG_CONFIG_HOME}/qt5ct"
        mkdir -p "${qt5ct_dest}"
        deploy_config "gtk/qt5ct.conf" "${qt5ct_dest}/qt5ct.conf"
    fi

    # xsettingsd
    if [[ -f "${REPO_ROOT}/gtk/xsettingsd.conf" ]]; then
        deploy_config "gtk/xsettingsd.conf" "${XDG_CONFIG_HOME}/xsettingsd/xsettingsd.conf"
    fi

    log_ok "GTK configuration deployed."
}

deploy_theme_config() {
    log_info "Deploying theme configuration..."

    # Deploy theme.conf and env.conf to the config directory.
    local themes_dest="${XDG_CONFIG_HOME}/themes"
    mkdir -p "${themes_dest}"

    if [[ -f "${REPO_ROOT}/themes/theme.conf" ]]; then
        deploy_config "themes/theme.conf" "${themes_dest}/theme.conf"
    fi

    if [[ -f "${REPO_ROOT}/themes/env.conf" ]]; then
        deploy_config "themes/env.conf" "${themes_dest}/env.conf"
    fi

    # Deploy cursor theme index.
    if [[ -f "${REPO_ROOT}/themes/index.theme" ]]; then
        local icons_dest="${HOME}/.local/share/icons/default"
        mkdir -p "${icons_dest}"
        deploy_config "themes/index.theme" "${icons_dest}/index.theme"
    fi

    log_ok "Theme configuration deployed."
}

setup_cursor_theme() {
    log_info "Setting cursor theme..."

    # Set cursor theme via environment.d for Hyprland.
    local env_dir="${XDG_CONFIG_HOME}/environment.d"
    mkdir -p "${env_dir}"

    local cursor_conf="${env_dir}/cursor.conf"
    if [[ ! -f "${cursor_conf}" ]]; then
        cat > "${cursor_conf}" <<'EOF'
# Cursor theme for Wayland compositors.
# Generated by project_arch Layer 5.
XCURSOR_THEME=Bibata-Modern-Ice
XCURSOR_SIZE=24
HYPRCURSOR_THEME=Bibata-Modern-Ice
HYPRCURSOR_SIZE=24
EOF
        log_ok "Cursor environment variables written to ${cursor_conf}"
    else
        log_info "Cursor config already exists: ${cursor_conf}"
    fi
}

refresh_font_cache() {
    log_info "Refreshing font cache..."

    if command_exists fc-cache; then
        fc-cache -fv > /dev/null 2>&1
        log_ok "Font cache refreshed."
    else
        log_warn "fc-cache not found — font cache not updated."
    fi
}

# =============================================================================
# Main
# =============================================================================

main() {
    layer_banner "Layer 5 — Theming" "GTK, icons, cursors, and fonts"

    require_not_root
    require_layer 4

    # Install packages.
    log_section "Installing Layer 5 Packages"
    install_packages "Theming & Fonts" "${LAYER5_PACKAGES[@]}"
    install_aur_packages "Cursor Theme" "${LAYER5_AUR_PACKAGES[@]}"

    # Deploy configs.
    log_section "Deploying Layer 5 Configuration"
    deploy_gtk_config
    deploy_theme_config
    setup_cursor_theme
    refresh_font_cache

    # Summary.
    log_section "Layer 5 Installation Complete"
    echo -e "  ${COLOR_GREEN}${COLOR_BOLD}Layer 5 is complete.${COLOR_RESET}"
    echo ""
    echo -e "  ${COLOR_CYAN}Next steps:${COLOR_RESET}"
    echo -e "  1. Run  ${COLOR_BOLD}bash install/verify_layer5.sh${COLOR_RESET}  to verify."
    echo -e "  2. Use ${COLOR_BOLD}nwg-look${COLOR_RESET} to preview GTK themes."
    echo -e "  3. When ready, proceed to Layer 6: ${COLOR_BOLD}bash install/layer6.sh${COLOR_RESET}"
    echo ""
}

main "$@"
